/*
 * generated by Xtext
 */
package de.integrity.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return de.integrity.ui.internal.DSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return de.integrity.ui.internal.DSLActivator.getInstance().getInjector("de.integrity.DSL");
	}
	
}
