/*
 * generated by Xtext
 */
package de.integrity.ui.contentassist;

import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.jdt.core.IJavaElement;
import org.eclipse.jdt.core.JavaModelException;
import org.eclipse.jdt.internal.core.CompilationUnit;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.common.types.util.jdt.IJavaElementFinder;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;

import com.google.inject.Inject;

import de.integrity.dsl.Call;
import de.integrity.dsl.CallDefinition;
import de.integrity.dsl.MethodReference;
import de.integrity.dsl.Parameter;
import de.integrity.dsl.ParameterTableHeader;
import de.integrity.dsl.TableTest;
import de.integrity.dsl.Test;
import de.integrity.dsl.TestDefinition;
import de.integrity.fixtures.ArbitraryParameterFixture;
import de.integrity.fixtures.ArbitraryParameterFixture.ArbitraryParameterDefinition;
import de.integrity.fixtures.Fixture;
import de.integrity.ui.JavadocUtil;
import de.integrity.ui.utils.ClassLoadingUtil;
import de.integrity.utils.IntegrityDSLUtil;
import de.integrity.utils.ParamAnnotationTuple;

/**
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on
 * how to customize content assistant
 */
@SuppressWarnings("restriction")
public class DSLProposalProvider extends AbstractDSLProposalProvider {

	@Inject
	IJavaElementFinder elementFinder;

	@Override
	public void completeTest_Parameters(EObject model, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeTest_Parameters(model, assignment, context, acceptor);

		Test tempTest = (Test) model;
		TestDefinition tempTestDef = tempTest.getDefinition();
		if (tempTestDef != null) {
			Set<String> tempAlreadyUsedParameters = new HashSet<String>();
			for (Parameter tempParameter : tempTest.getParameters()) {
				tempAlreadyUsedParameters.add(IntegrityDSLUtil.getParamNameStringFromParameterName(tempParameter
						.getName()));
			}
			completeParametersInternal(tempAlreadyUsedParameters, tempTestDef.getFixtureMethod(), null, context,
					acceptor);
		}
	}

	@Override
	public void completeCall_Parameters(EObject model, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeCall_Parameters(model, assignment, context, acceptor);

		Call tempCall = (Call) model;
		CallDefinition tempCallDef = tempCall.getDefinition();
		if (tempCallDef != null) {
			Set<String> tempAlreadyUsedParameters = new HashSet<String>();
			for (Parameter tempParameter : tempCall.getParameters()) {
				tempAlreadyUsedParameters.add(IntegrityDSLUtil.getParamNameStringFromParameterName(tempParameter
						.getName()));
			}
			completeParametersInternal(tempAlreadyUsedParameters, tempCallDef.getFixtureMethod(), null, context,
					acceptor);
		}
	}

	@Override
	public void completeTableTest_Parameters(EObject model, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeTableTest_Parameters(model, assignment, context, acceptor);

		TableTest tempTableTest = (TableTest) model;
		TestDefinition tempTestDef = tempTableTest.getDefinition();
		if (tempTestDef != null) {
			Set<String> tempAlreadyUsedParameters = new HashSet<String>();
			for (Parameter tempParameter : tempTableTest.getParameters()) {
				tempAlreadyUsedParameters.add(IntegrityDSLUtil.getParamNameStringFromParameterName(tempParameter
						.getName()));
			}
			for (ParameterTableHeader tempHeader : tempTableTest.getHeaders()) {
				tempAlreadyUsedParameters
						.add(IntegrityDSLUtil.getParamNameStringFromParameterName(tempHeader.getName()));
			}

			completeParametersInternal(tempAlreadyUsedParameters, tempTestDef.getFixtureMethod(), null, context,
					acceptor);
		}
	}

	@Override
	public void completeTableTest_Headers(EObject model, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeTableTest_Headers(model, assignment, context, acceptor);

		TableTest tempTableTest = (TableTest) model;
		TestDefinition tempTestDef = tempTableTest.getDefinition();
		if (tempTestDef != null) {
			Set<String> tempAlreadyUsedParameters = new HashSet<String>();
			for (Parameter tempParameter : tempTableTest.getParameters()) {
				tempAlreadyUsedParameters.add(IntegrityDSLUtil.getParamNameStringFromParameterName(tempParameter
						.getName()));
			}
			for (ParameterTableHeader tempParameterHeader : tempTableTest.getHeaders()) {
				tempAlreadyUsedParameters.add(IntegrityDSLUtil.getParamNameStringFromParameterName(tempParameterHeader
						.getName()));
			}
			completeParametersInternal(tempAlreadyUsedParameters, tempTestDef.getFixtureMethod(), "| ", context,
					acceptor);
		}
	}

	@Override
	public void completeParameterTableHeader_Name(EObject model, Assignment assignment, ContentAssistContext context,
			ICompletionProposalAcceptor acceptor) {
		super.completeParameterTableHeader_Name(model, assignment, context, acceptor);

		TableTest tempTableTest = (TableTest) model;
		TestDefinition tempTestDef = (tempTableTest).getDefinition();
		if (tempTestDef != null) {
			Set<String> tempAlreadyUsedParameters = new HashSet<String>();
			for (ParameterTableHeader tempParameterHeader : tempTableTest.getHeaders()) {
				tempAlreadyUsedParameters.add(IntegrityDSLUtil.getParamNameStringFromParameterName(tempParameterHeader
						.getName()));
			}
			completeParametersInternal(tempAlreadyUsedParameters, tempTestDef.getFixtureMethod(), null, context,
					acceptor);
		}
	}

	private void completeParametersInternal(Set<String> someAlreadyUsedParameters, MethodReference aMethod,
			String aPrefix, ContentAssistContext aContext, ICompletionProposalAcceptor anAcceptor) {

		Map<String, String> tempJavadocMap = JavadocUtil.getMethodParamJavadoc(aMethod.getMethod(), elementFinder);

		List<ParamAnnotationTuple> tempParamList = IntegrityDSLUtil.getAllParamNamesFromFixtureMethod(aMethod);
		for (ParamAnnotationTuple tempParam : tempParamList) {
			if (!someAlreadyUsedParameters.contains(tempParam.getParamName())) {
				String tempJavadocDescription = tempJavadocMap != null ? tempJavadocMap.get(tempParam
						.getJavaParamName()) : null;
				String tempDisplayText = null;
				if (tempJavadocDescription != null) {
					tempDisplayText = tempParam.getParamName() + ": " + tempJavadocDescription;
				} else {
					tempDisplayText = tempParam.getParamName();
				}
				anAcceptor.accept(createCompletionProposal((aPrefix != null ? aPrefix : "") + tempParam.getParamName(),
						tempDisplayText, null, aContext));
			}
		}
	}

	@Override
	public void completeArbitraryParameterName_Identifier(EObject model, Assignment assignment,
			ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
		super.completeArbitraryParameterName_Identifier(model, assignment, context, acceptor);

		Parameter tempParameter = (Parameter) model.eContainer();
		Map<String, Object> tempParameterMap = null;

		MethodReference tempMethodReference = null;
		if (tempParameter.eContainer() instanceof Test) {
			Test tempTest = (Test) tempParameter.eContainer();
			tempParameterMap = IntegrityDSLUtil.createParameterMap(tempTest.getParameters(), null, true);
			tempMethodReference = tempTest.getDefinition().getFixtureMethod();
		} else if (tempParameter.eContainer() instanceof Call) {
			Call tempCall = (Call) tempParameter.eContainer();
			tempParameterMap = IntegrityDSLUtil.createParameterMap(tempCall.getParameters(), null, true);
			tempMethodReference = tempCall.getDefinition().getFixtureMethod();
		}

		if (tempParameterMap != null && tempMethodReference != null && tempMethodReference.getType() != null) {
			IJavaElement tempSourceMethod = (IJavaElement) elementFinder.findElementFor(tempMethodReference.getType());

			CompilationUnit tempCompilationUnit = (CompilationUnit) tempSourceMethod.getParent();
			Class<?> tempFixtureClass;
			try {
				tempFixtureClass = ClassLoadingUtil.loadClassFromWorkspace(
						tempCompilationUnit.getTypes()[0].getFullyQualifiedName(), tempSourceMethod.getJavaProject());
				Fixture tempFixtureInstance = (Fixture) tempFixtureClass.newInstance();

				if (tempFixtureInstance instanceof ArbitraryParameterFixture) {
					Map<String, Object> tempFixedParameterMap = null;
					if (tempParameter.eContainer() instanceof Test) {
						Test tempTest = (Test) tempParameter.eContainer();
						tempFixedParameterMap = IntegrityDSLUtil.createParameterMap(tempTest.getParameters(), null,
								false);
					} else if (tempParameter.eContainer() instanceof Call) {
						Call tempCall = (Call) tempParameter.eContainer();
						tempFixedParameterMap = IntegrityDSLUtil.createParameterMap(tempCall.getParameters(), null,
								false);
					}

					List<ArbitraryParameterDefinition> tempParameterDescriptions = ((ArbitraryParameterFixture) tempFixtureInstance)
							.defineArbitraryParameters(tempMethodReference.getMethod().getSimpleName(),
									tempFixedParameterMap);
					for (ArbitraryParameterDefinition tempParameterDescription : tempParameterDescriptions) {
						String tempName = tempParameterDescription.getName();
						if (!tempParameterMap.containsKey(tempName)) {
							String tempDescription = tempName;
							if (tempParameterDescription.getDescription() != null) {
								tempDescription += ": " + tempParameterDescription.getDescription();
							}
							acceptor.accept(createCompletionProposal(tempName, tempDescription, null, context));
						}
					}
				}
			} catch (ClassNotFoundException exc) {
				exc.printStackTrace();
			} catch (InstantiationException exc) {
				exc.printStackTrace();
			} catch (IllegalAccessException exc) {
				exc.printStackTrace();
			} catch (JavaModelException exc) {
				exc.printStackTrace();
			}

		}
	}
}
