/*
* generated by Xtext
*/
package de.gebit.integrity.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class DSLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
